#!/bin/bash
# Automate the process of making API requests to the Pokémon API and saving the results to a file

#set -x

API_URL='https://pokeapi.co/api/v2/pokemon/pikachu'

# Make the API request and store the response
response=$(curl -s -X GET $API_URL)

# Check if the curl command was successful
if [ $? -ne 0 ]; then
    echo "Error occurred while making the API call." 2> error.txt
else
    echo "$response" > data.json
fi

