#!/bin/bash
# Automate the process of making API requests to the Pokémon API and saving the results to a file

#set -x

POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

for POKEMON in "${POKEMONS[@]}"; do
    API_URL="https://pokeapi.co/api/v2/pokemon/${POKEMON}"

    # Make the API request and store the response
    response=$(curl -s -X GET $API_URL)

    # Check if the curl command was successful
    if [ $? -ne 0 ]; then
        echo "Error occurred while making the API call for $POKEMON." 2> errors.txt
    else
        echo "$response" > "${POKEMON}.json"
    fi

    # Delay between requests
    sleep 2
done