#!/bin/bash

JSON_FILE="data.json"

name=$(jq -r '.name' "$JSON_FILE")
height=$(jq -r '.height' "$JSON_FILE")
weight=$(jq -r '.weight' "$JSON_FILE")
type=$(jq -r '.types[0].type.name' "$JSON_FILE")

formatted_height=$(awk "BEGIN {printf \"%.1f\", $height / 10}")
formatted_weight=$(awk "BEGIN {printf \"%.1f\", $weight / 10}")

type=$(echo "$type" | sed 's/^./\U&/')
formatted_output="$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
echo "$formatted_output"

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."