#!/bin/bash

JSON_FILE="data.json"

name=$(jq -r '.name' "$JSON_FILE")
height=$(jq -r '.height' "$JSON_FILE")
weight=$(jq -r '.weight' "$JSON_FILE")
type=$(jq -r '.types[0].type.name' "$JSON_FILE")

height_m=$(awk "BEGIN {printf \"%.1f\", $height / 10}")
weight_kg=$(awk "BEGIN {printf \"%.1f\", $weight / 10}")

type=$(echo "$type" | sed 's/^./\U&/')
formatted_output="$name is of type $type, weighs ${weight_kg}kg, and is ${height_m}m tall."
echo "$formatted_output"
